name: Create Release Pull pull-requests

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags, required for Lerna (default is 1)
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Version Bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          corepack enable
          git config user.name "aversini"
          git config user.email "versini@gmail.com"
          mkdir tmp
          echo ":rocket: Automated Version Bump " > tmp/version-bump.md
          echo "---" >> tmp/version-bump.md
          echo "" >> tmp/version-bump.md
          echo "### List of updated package(s)" >> tmp/version-bump.md
          echo "" >> tmp/version-bump.md
          npx lerna changed --conventional-commits --loglevel=error | sed 's/^/- /' >> tmp/version-bump.md
          echo "" >> tmp/version-bump.md
          echo "" >> tmp/version-bump.md
          npx lerna version --exact --conventional-commits --no-private --yes --no-push

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PR_WRITE }}
          delete-branch: true
          title: "chore: release main"
          body-path: |
            tmp/version-bump.md
          labels: |
            autorelease
